INSERT INTO transactions.transaction_type (code, name, description) VALUES ('DATALOAD', 'Initial data load', 'Initial load when we take on the register') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('ADDITION', 'Addition') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name, description) VALUES ('WIP_XFER', 'WIP Transfer', 'Transfer from Work In Progress') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('DEPRECIATE', 'Depreciate') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('UPGRADE', 'Upgrade') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('IMPAIR', 'Impair') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('REVALUE', 'Revalue') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('MAINT', 'Maintenance') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('RECLASSIF', 'Reclassify') ON CONFLICT(code) DO NOTHING;
INSERT INTO transactions.transaction_type (code, name) VALUES ('DERECOG', 'Derecognise') ON CONFLICT(code) DO NOTHING;