  # -- add to your compose file

  #
  # Core Asset Service
  #
  asset-core-service:
    image: imqs/asset-core-service:master
    ports:
      - "127.0.0.1:8669:80"
    volumes:
      - ./logs:/var/log/imqs
    depends_on:
      - config
      - db
      - router
      - auth
    #environment:
      # valid values are "test", "production" and "admin"
      # "test" exposes additional endpoints to aid integration testing
      # "admin" should not be used under nornal circumstances - ask before you do
      #- spring_profiles_active=test